apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invalid-pvc-datasource
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    apiGroup: invalid.storage.k8s.io
    kind: Invalid
    name: invalid
