apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valid-pvc-datasource
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    apiGroup: valid.storage.k8s.io
    kind: Valid
    name: valid
